[project]
name = "makestx"
description = "MakeSTX Cyberpunk NFT — 10,000 Supply, Free Mint on Stacks"
authors = []
telemetry = false

[contracts.makestx-nft]
path = "contracts/makestx-nft.clar"
clarity_version = 2
epoch = "2.5"
